version: "3"
services:
    educatifyapp:
        build: .
        ports: 
            - "80:4200"
        volumes: 
            - "/app/node_modules"
            - ".:/app"
    strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
